### ISSUE TITLE
can anybody tell me where is the following file vali_modified.csv

### ISSUE THREAD

**Issue by khalid5454** [wenxinxu/deep-shopping#3]
path = 'data/vali_modified.csv'
df = pd.read_csv(path)

**Comment by wenxinxu** [comment]
Hi, Just added the csv file!

**Comment by khalid5454** [comment]
Thanks a lot let me check

**Comment by khalid5454** [comment]
can you add a demo how to input test image for recommending similar images

**Comment by khalid5454** [comment]
while running the whole project  getting no result
