### ISSUE TITLE
While running the project get following error 

### ISSUE THREAD

**Issue by khalid5454** [wenxinxu/deep-shopping#7]
File "pandas/_libs/parsers.pyx", line 387, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 705, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'data/train_modified2.csv' does not exist: b'data/train_modified2.csv'

train_modified2.csv is missing @wenxinxu

**Comment by young-yangb** [comment]
@khalid5454  
I have encountered the same problem...Have you solved that?

**Comment by khalid5454** [comment]
Hi, you can use the other file train_modified.csv or rename this one to  train_modified.csv then it will work.
Thanks

**Comment by young-yangb** [comment]
I split the "vali_modified.csv" into train/val/test and it works.
When I finished, I got a (25,64) nadarry, and I thought 25 represents the last 25 image in test set, but what does 64 mean?
